### ISSUE TITLE
Error in `parse_hmmdomtbl`, else statement provides 14 values when 15 required 

### ISSUE THREAD

**Issue by alexdthomas** [jwestrob/GOOSOS#1]
Running the following command
```
echo "python ~/apps/GOOSOS/GOOSOS.py -nucdir /data4/EastRiver/Vegtype/data/genomes/dRep_strain/data/prodigal/fna_files -hmmdir /home/jwestrob/hmms/Hug_et_al -outdir /data4/EastRiver/Vegtype/data/GOOSOS -evalue 1e-10 -threads 48" | qsub -V
```
Crashed the program after producing the `hmmpress`, `hmmscan`, and `proteins` directories with the following error.

```
multiprocess.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/multiprocess/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/multiprocess/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "/home/talex/apps/GOOSOS/GOOSOS.py", line 407, in run_hmms
    return run_hmmscan(fastafile, outdir, threshold)
  File "/home/talex/apps/GOOSOS/GOOSOS.py", line 82, in run_hmmscan
    return parse_hmmdomtbl(outdir, genome_id + '_hmmsearch.out', threshold)
  File "/home/talex/apps/GOOSOS/GOOSOS.py", line 311, in parse_hmmdomtbl
    orf_df = pd.DataFrame(orflist, columns=orflist_header)
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pandas/core/frame.py", line 305, in __init__
    arrays, columns = _to_arrays(data, columns, dtype=dtype)
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pandas/core/frame.py", line 5519, in _to_arrays
    dtype=dtype)
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pandas/core/frame.py", line 5598, in _list_to_arrays
    coerce_float=coerce_float)
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pandas/core/frame.py", line 5657, in _convert_object_array
    'columns' % (len(columns), len(content)))
AssertionError: 15 columns passed, passed data had 14 columns
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/talex/apps/GOOSOS/GOOSOS.py", line 473, in <module>
    run_workflow()
  File "/home/talex/apps/GOOSOS/GOOSOS.py", line 409, in run_workflow
    hmm_outfiles = list(p.map(run_hmms, protlist_wpath))
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pathos/multiprocessing.py", line 137, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/multiprocess/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/multiprocess/pool.py", line 644, in get
    raise self._value
AssertionError: 15 columns passed, passed data had 14 columns
```

My guess is an error in `parse_hmmdomtbl`, line 308 needs another NaN.  That code block under the `else` statement has 14 values, but the block above starting line 276 has 15...

**Comment by alexdthomas** [comment]
Changed line 308 to include another NaN.  Reran with 
```
python ~/apps/GOOSOS/GOOSOS.py -nucdir /data4/EastRiver/Vegtype/data/genomes/dRep_strain/data/prodigal/fna_files -hmmdir /home/jwestrob/hmms/Hug_et_al -outdir /data4/EastRiver/Vegtype/data/GOOSOS -evalue 1e-10 -threads 6 -already_predicted -already_scanned
```
Crashed with following error
```
/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Bio/SearchIO/__init__.py:211: BiopythonExperimentalWarning: Bio.SearchIO is an experimental submodule which may undergo significant changes prior
to its future official release.
  BiopythonExperimentalWarning)
Traceback (most recent call last):
  File "/home/talex/apps/GOOSOS/GOOSOS.py", line 473, in <module>
    run_workflow()
  File "/home/talex/apps/GOOSOS/GOOSOS.py", line 422, in run_workflow
    all_df = pd.concat(all_df_list, sort=False)
TypeError: concat() got an unexpected keyword argument 'sort'
```

Changed line 422 from `all_df = pd.concat(all_df_list, sort=False)` to `all_df = pd.concat(all_df_list)`.  Reran `python ~/apps/GOOSOS/GOOSOS.py -nucdir /data4/EastRiver/Vegtype/data/genomes/dRep_strain/data/prodigal/fna_files -hmmdir /home/jwestrob/hmms/Hug_et_al -outdir /data4/EastRiver/Vegtype/data/GOOSOS -evalue 1e-10 -threads 6 -already_predicted -already_scanned`

Got error 
```
/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/Bio/SearchIO/__init__.py:211: BiopythonExperimentalWarning: Bio.SearchIO is an experimental submodule which may undergo significant changes prior
to its future official release.
  BiopythonExperimentalWarning)
Traceback (most recent call last):
  File "/home/talex/apps/GOOSOS/GOOSOS.py", line 473, in <module>
    run_workflow()
  File "/home/talex/apps/GOOSOS/GOOSOS.py", line 422, in run_workflow
    all_df = pd.concat(all_df_list)
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pandas/tools/merge.py", line 1451, in concat
    copy=copy)
  File "/home/talex/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pandas/tools/merge.py", line 1484, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate
```
Maybe an error in `run_hmms` that paths to files in the `hmmscan` dir correctly?

**Comment by jwestrob** [comment]
Looks like the hmm_outfiles variable is empty when it reaches  `all_df_list = list(p.map(lambda x: pd.read_csv(x, sep='\t'), hmm_outfiles))`. I'm on the case

**Comment by jwestrob** [comment]
Fixed. The issue is that the `concat` flag in `pd.concat` was added in pandas 0.23, which was a more recent version than was being used to run GOOSOS. For anyone who runs into this issue, please update pandas through uninstalling and reinstalling.
